### ISSUE TITLE
[wibni] Change URL

### ISSUE THREAD

**Issue by aatifsyed** [ChainSafe/forest-explorer#10]
We currently have:
- https://docs.forest.chainsafe.io/rustdoc/ for rustdoc
- https://docs.forest.chainsafe.io/ for the book
- https://forest.chainsafe.io/ for the product

WIBNI https://explorer.forest.chainsafe.io

**Comment by ruseinov** [comment]
It depends. "Forest Explorer" is a dedicated product meant to be something like `filfox`. Then it does not necessarily need to live under `forest` subdomain. I have no strong opinion on the subject though.

**Comment by aatifsyed** [comment]
@lemmih can you `convert issue to discussion`, that's probably a more appropriate place then, but I don't have permissions

**Comment by lemmih** [comment]
> @lemmih can you `convert issue to discussion`, that's probably a more appropriate place then, but I don't have permissions

Hmm, I don't have permission, either. But I do like the `explorer.forest.chainsafe.io` name. I only have access to the `chainsafe.dev` domain so we'll have to rope in someone from the infrastructure team.

**Comment by LesnyRumcajs** [comment]
I don't see a strong push for this, and we already _advertised_ the current name. Closing until a wild champion appears with a strong opinion and will to push it forward.
