### ISSUE TITLE
Copy enough code from Forest to sign a message

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest-explorer#9]
Implementing a Filecoin faucet requires signing messages. Forest has the code for signing messages but is not available as an independent crate.

We need:
- `forest_filecoin::key_management::keystore::KeyInfo`
- `forest_filecoin::key_management::wallet::Key`
- `crate::key_management::sign`

Both `SignatureType::Bls` and `SignatureType::Secp256k1` have to be supported.

Test by importing a key and signing a test message. The output should be identical to `forest-wallet sign -m [MSG]`.

**Comment by LesnyRumcajs** [comment]
Does the code need to be copied? Could we re-use instead by adding `forest-filecoin` into the dependencies? This might require some visibility changes in the `forest-filecoin` crate, but otherwise should be feasible.

**Comment by lemmih** [comment]
I'm fairly sure `forest-filecoin` doesn't compile to WASM. But splitting off smaller crates is certainly a future goal.

**Comment by LesnyRumcajs** [comment]
@lemmih Is this already done?

**Comment by lemmih** [comment]
Done!
