### ISSUE TITLE
Send on enter

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest-explorer#90]
# Summary

Currently, send is only done by clicking the `Send` button. Allowing the use of `Enter` would feel more natural for those Vim Zealots who avoid using the mouse.

# Completion Criteria

- [ ] pressing `Enter` sends the funds, same as the button `send`

# Additional Links & Resources

**Comment by LesnyRumcajs** [comment]
Couldn't do it before holidays, unassigning myself. Should be easier to do once https://github.com/ChainSafe/forest-explorer/pull/95 is merged.

**Comment by elmattic** [comment]
Note that as a workaround, you can press Tab to focus on the button and then press Enter. 😉
